name: AdvancedReplay
version: '${version}'
main: me.jumper251.replay.ReplaySystem
authors:
  - Jumper251
  - 404
depend: [ProtocolLib]
api-version: 1.20
folia-supported: true
libraries:
  - org.mongodb:mongodb-driver-sync:5.2.0
  - com.github.luben:zstd-jni:1.5.6-8
  - org.lz4:lz4-java:1.8.0
commands:
  replay:
    description: Main Replay command
    aliases: [rp]
    permission: replay.command

permissions:
  replay.command:
    description: Permission to use the replay command
  replay.command.start:
    default: op
  replay.command.stop:
    default: op
  replay.command.info:
    default: op
  replay.command.play:
    default: op
  replay.command.reload:
    default: op
  replay.command.overview:
    default: op
  replay.command.list:
    default: op
  replay.command.migrate:
    default: op
  replay.command.delete:
    default: op
  replay.command.jump:
    default: op
  replay.admin:
    description: Permission to receive update notifications